{{- if .Values.global.serviceaccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.global.serviceaccount.name | default (printf "%s-sa" .Release.Name) }}
  labels:
{{- include "sdm.labels" . | nindent 4 }}
{{- if .Values.global.serviceaccount.annotations }}
  annotations: {{ toYaml .Values.global.serviceaccount.annotations | nindent 4 }}
{{- end }}
{{- end -}}
